### ISSUE TITLE
Email notices for new user registration not received

### ISSUE THREAD

**Issue by tz-earl** [NYC-Camp/website#11]
Created three users using email accounts on different services. This is what happened with the initial email notices: 

fastmail.fm - got the email
zoho.com - went to spam
gmail.com - never got it; not in spam

**Comment by ForestMars** [comment]
Earl, can you please file this in the Pantheon support queue? We don't really have access to their mail server logs.

**Comment by tz-earl** [comment]
Forest, I opened a ticket at Pantheon. Requested access to email logs and any other ideas they may have for troubleshooting.

Question to Pantheon: "Do you have any suggestions for troubleshooting this?"

Pantheon responded: "Not really. Because of our cloud infrastructure, email may come from many IP addresses and be affected by any specific companies' firewall rules. The best recommendation when sending more than typical transactional email is to use sendgrid. Sendgrid makes all email delivery problems basically stop, for what it is worth. We get notices via google, we use their service internally, so I can't explain that. Most likely it was sent if the others worked. Hope that helps."

**Comment by tz-earl** [comment]
Integrating SendGrid into Drupal:

http://sendgrid.com/docs/Integrate/Open_Source_Apps/drupal.html

**Comment by tz-earl** [comment]
"Email on Pantheon"  http://helpdesk.getpantheon.com/customer/portal/articles/515937

"Using SendGrid for Outbound Email"  http://helpdesk.getpantheon.com/customer/portal/articles/1153430-using-sendgrid-for-outbound-email

**Comment by mirie** [comment]
I set up a SendGrid account for NYC Camp.

**Comment by ForestMars** [comment]
How it's it that we didn't need this last year?

**Comment by mirie** [comment]
@ForestMars, I don't know.

I setup the smtp module and added in the sendgrid creds on Prod. @tz-earl, @Offlein, @likewhoa and a friend of mine all tested a number of unique email accounts without issue.

**Comment by mirie** [comment]
I think this is resolved. closing this out.
