### ISSUE TITLE
"NYC Camp 14" has typos, etc.

### ISSUE THREAD

**Issue by tz-earl** [NYC-Camp/website#110]
Text content of "NYC Camp 14" has typos and needs other minor corrections.

http://test-nyccamp2014.gotpantheon.com/nyc-camp-14

**Comment by tz-earl** [comment]
Made corrections. Needs review.

http://test-nyccamp2014.gotpantheon.com/nyc-camp-14

**Comment by likewhoa** [comment]
A few corrections...

April 10th through the 13th.

At that time, you will be able to sign-up to attend these events which will have limited capacity. Registration must be confirmed to attend all events.

**Comment by tz-earl** [comment]
Wow, all the text edits I did this morning disappeared, as though they never happened. I just did those changes again and cleared caches. The end of the first paragraph should exactly read "from April 10th through the 13th" as suggested above by likewhoa. If you don't see that, something is screwy.  Needs review, again.  http://test-nyccamp2014.gotpantheon.com/nyc-camp-14

**Comment by ForestMars** [comment]
Did we ever figure out what happened? We need to pay attention to gaps in our process and tighten up. Today's missing text is tomorrow's nasty regression, or worse a regression that isn't caught right away.

**Comment by tz-earl** [comment]
@forest No explanation so far. I'm wondering if my text edits were overwritten because the database from live was copied into test, where I did the work. Is anything like that happening automatically?

**Comment by ForestMars** [comment]
Oh that would definitely explain it. The live db is regularly pulled down to test, albeit not automatically.

**Comment by tz-earl** [comment]
About an hour ago, Mai pulled the live db down to test, which overwrote the content changes I made and explains what happened yesterday when those same changes disappeared. Since these are just minor edits of typos and such, I'll apply them in live.

**Comment by tz-earl** [comment]
Made these text edits in live.  http://nyccamp.org/nyc-camp-14
