### ISSUE TITLE
Add an QR code tab to the user's profile.

### ISSUE THREAD

**Issue by esod** [NYC-Camp/website#114]
I've added a QR code to the user's profile. I've deployed the QR code to:

http://qr-code3-nyccamp2014.gotpantheon.com/users/nyc-camp

I'm not certain what we want to include in the QR code, but changing its contents will be simple since the user field, field_mobile_code accepts tokens. Currently the only field in the QR code is the user's first name, [current-user:field-profile-first]. Note that like personal schedules, you may view your qr-code only. QR codes are not publicly shared. 

TODO: Confirm that the first name field is in the QR code.

For existing users I've set up a rule to set a data value for the field_mobile_code and change its text format when User account is viewed. The rule will be helpful for on-the-fly changes to the QR code should that need arise.

I've pushed the code to the upstream in a branch called qr-code. The feature module is called QR code (qr_code). Enable the module and let me know what you think.

**Comment by likewhoa** [comment]
I got a few questions and concerns regarding the qr-code implementation.
- Why have a non-public qr-core? the point of a qr-code is to have another way to promote something. Perhaps users should be allowed to set their qr-core for public viewing.
- Need a proper error page for users that try to view a qr-core which is not public, currently it's a 404
- Better explanation to end users on how to enter qr-code info to their profile, I believe some users will want access as to what goes into their qr-code specially if they which to have it set to public viewing.

Personally I think a qr-code would be best suited for the directions,venue and other pages that could hold useful info.

**Comment by robbiethegeek** [comment]
The idea was that users can have a QR code, so the checkin application has a simple way to allow a user to walk up and have a print out with the QR code or their phone via their profile page.

**Comment by esod** [comment]
If we opened the qr field to users, there would be confusion and failure because of the requirement of the text format on the field and the requirement of the method calls in the field. Plus the field accepts tokens, which we can change, of course. Anyway we're not thinking of this field as a user enabled field.

Do you have a suggestion on another error page besides the 404 page with a custom message like I've implemented?

**Comment by likewhoa** [comment]
@esod I mean allow users to control the privacy setting for this qr-core so that if they wish it can be made public. We should handle what goes in the field as to not confuse users on how to generate them.

The 404 should just be custom with a message like you have and nothing more. Perhaps one with a qr-core to a bunch of links to the camp ;)

**Comment by esod** [comment]
cool @likewhoa. Let's find out what we want to put in the qr-code. The privacy settings can be extended to the user without difficulty.

I think we're talking about a custom 404 page, in general, which we do not have. Then specifically, we can insert into it messages that are within context.

**Comment by esod** [comment]
I confirm that the QR codes contain the token data!

**Comment by likewhoa** [comment]
Thanks for this @esod, do open a new task for the field permissions and 404 page.
