### ISSUE TITLE
After registering for the conference, the registration block remains

### ISSUE THREAD

**Issue by mirie** [NYC-Camp/website#119]
Steps to reproduce:
1. Go to your user page and click to register for the conference
2. The next time you visit your user page, it will look like you still need to register for the conference because the block is still there.

The only indication that you've already registered, is an error message informing the user that s/he has already registered.

It would be better to replace this block with either the My Schedules feature @esod created, or direct the user to whatever gets setup in #117. In any case, we need at minimum language informing the user that s/he is already registered.

**Comment by esod** [comment]
I think we've made progress on this issue and I'm going to close it. Check out the site now. When you're unregistered, the block says one thing and the form behaves one way. When you're registered, the block says something else and the form behaves another way. It's not perfect, but this issue has got some forward momentum and I know what we're trying for, so I'm going to close this issue.
