### ISSUE TITLE
Unable to evaluate action og_subcribe_user error when registering a new account

### ISSUE THREAD

**Issue by mirie** [NYC-Camp/website#13]
This is an error that occurs everytime a new account is created via /user/register. The error message points to this Rule config page:

http://nyccamp.org/admin/config/workflow/rules/components/manage/rules_add_new_user_to_default_event_group/edit/3

**Comment by likewhoa** [comment]
this might be an issue with current entity. see https://drupal.org/node/1894326 and comment number 7. I will look into this further tomorrow.

**Comment by mirie** [comment]
I disabled this Rule. This is not even being used anymore.
