### ISSUE TITLE
Make "broken" time slot fields not required and hides them.

### ISSUE THREAD

**Issue by esod** [NYC-Camp/website#134]
Until we're certain Time Session Slot(s) was a  misstep from the COD development team, I want to keep the fields in the system. But they need to be not required and hidden to avoid frustration and confusion.

**Comment by ForestMars** [comment]
> "Until we're certain Time Session Slot(s) was a misstep from the COD development team"

Well, yes. Is there a specific upstream issue that someone was referencing? Because really, they either are or are not a "misstep" from the COD team, and it's easy enough to reference this upstream, or simply file an issue there. 

This really underscores the need for our "fixing distribution features" branch. cc @scottrigby

**Comment by esod** [comment]
When time permits, I plan to add the issue to the upstream issue queue.

**Comment by esod** [comment]
I can't recreate the SQL error in the view on cod-7.x-1.0-alpha5 oob. I think what tripped us up was that <code>Content entity referenced from field_session_timeslot(s)</code> was changed in the Drupal ecosystem from last year to this year to <code>Field collection item entity referenced from timeslot(s)</code>. The SQL error occurred because our relationship was now on a field collection when it had been previously on a Content.

I don't know what I can really add to the upstream issue queue other than a complaint about how <em>we</em> couldn't get the same thing to work from last year to this year.

It was good to take another look at this issue since I need to swap out <code>field_session_timeslot</code> with <code>field_session_time</code> in some of the displays. What's not so good is we're going to have to remember not to use <code>field_session_timeslot</code>, but to use <code>field_session_time</code> as we develop the view's displays. We can hide the field collection item  that contains <code>field_session_timeslot</code>on the node form but it's still going to be available in Views.
