### ISSUE TITLE
Error from views logged multiple times every time cache is cleared

### ISSUE THREAD

**Issue by mirie** [NYC-Camp/website#14]
When clearing the cache, this error appears multiple times:

Notice: Undefined index: field_collection_item in views_handler_field_field->access() (line 127 of /srv/bindings/4cd08556c3d6499990ae30bfff6750c9/code/profiles/cod/modules/contrib/views/modules/field/views_handler_field_field.inc).

**Comment by likewhoa** [comment]
we can ignore these notices by adding <code>ini_set('error_reporting', 'E_ALL ^ E_NOTICE');</code> t settings.php or define the variable in question. These undefined index notices are common in modules as I've ran into them many times.

**Comment by ForestMars** [comment]
++ for hiding notices for now. 

We don't really have the development resources to go after warnings, let alone notices!

**Comment by mirie** [comment]
All right. I posted this because I ran into problems based on the number of entities loaded and this error appeared several times locally. Several meaning, a whoooole lot.

**Comment by likewhoa** [comment]
ok, if you want this see my first pull request! \o/ https://github.com/NYC-Camp/website/pull/15

**Comment by likewhoa** [comment]
as per @mirie request, i have made a new pr at https://github.com/NYC-Camp/website/pull/19

**Comment by mirie** [comment]
This is being handled by https://github.com/NYC-Camp/website/pull/19.

@likewhoa, btw I don't think you need to create a new PR when making changes. You should be able to commit to that same feature branch.
