### ISSUE TITLE
Multiple presenters requested for Sessions

### ISSUE THREAD

**Issue by mirie** [NYC-Camp/website#146]
We received a request for multiple presenters for sessions by Cottser today. I think that's a good idea. Just opening this issue so we can all be on the same page about the change.

**Comment by mirie** [comment]
I changed the Presenters field to allow unlimited values (it was originally 1). This is done on Live.

**Comment by ForestMars** [comment]
Correct, this is definitely the way it was originally set up. Not sure how it got changed to only 1.
