### ISSUE TITLE
Orphan panels page (/submit-session)

### ISSUE THREAD

**Issue by likewhoa** [NYC-Camp/website#152]
We have a panel page that is referencing the old 'submit a session' block which was replaced in #59 

We need to know where this link was reference as we have a user that complained about the page which currently only has a title with the missing block-8.

Suggestion are to either remove this panels page or put the new block in place.

**Comment by mirie** [comment]
This was a menu item set under the About dropdown. I replaced the path to be `propose/session`

**Comment by mirie** [comment]
I also disabled that panels page (page-page_submit_session), might have been one from last year that was enabled.

**Comment by likewhoa** [comment]
we should remove that panels page as i don't see a use for it now.

**Comment by likewhoa** [comment]
@mirie what should we do here, I don't see a reason for keeping those pages and or this issue open anymore.

**Comment by mirie** [comment]
@likewhoa, ok, I deleted that page. Closing this.
