### ISSUE TITLE
Conference Admin still showing last years sessions

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#155]
Conference Admin should only show sessions for the active conference: 

http://nyccamp.org/conference-admin/sessions/
http://nyccamp.org/conference-admin/sessions/accepted

How is this supposed to work in COD? We don't want to jury rig our own solution when this is putatively a crucial part of the COD roadmap.

**Comment by likewhoa** [comment]
We could add a hidden filter which only shows nodes from the current year and or expose it to display from previous years.

**Comment by ForestMars** [comment]
Since this is obviously needed for the COD Roadmap, I filed an upstream issue, however we really shouldn't let upstream slow us down, especially since we are arguably getting ahead of the 7.x-dev mainline (even though we are technically still on alpha5.)

**Comment by likewhoa** [comment]
so a filter by date should be ideal? P.S what is the upstream issue url for reference?

**Comment by ForestMars** [comment]
I wouldn't call it ideal, but I expect it will work. To keep things simple, can we just filter by year, so we're not having to mess with months / dates / etc? 

The ideal would be to work with the COD team to determine what the best implementation is going to  be. Maybe at NYC Camp when Jason Yee will be here?

**Comment by likewhoa** [comment]
Sure, but in the meantime lets just add the year filter so we can focus on this years sessions.

**Comment by ForestMars** [comment]
This is the view that's being used: /admin/structure/views/view/cod_session_sessions_admin/edit

**Comment by likewhoa** [comment]
all done, close when reviewed.
