### ISSUE TITLE
Minor edits to content: typos, et al.

### ISSUE THREAD

**Issue by tz-earl** [NYC-Camp/website#169]
Made the following changes on live. Needs review.

http://nyccamp.org/event/drupal-8-core-sprint (corrected typos and misspellings)
http://nyccamp.org/directions  (added a link to NJ Transit)
http://nyccamp.org/partner  (missing punctuation in top portion)

**Comment by likewhoa** [comment]
@tz-earl I made a trello card which you and everyone should use to archive the pages and corrections which we are making for future reference. Please add there pages to that card. Thanks!

**Comment by tz-earl** [comment]
Made a near-complete pass on live to copy edit the published content (including accepted Sessions but not other proposed Sessions). Corrected dozens of minor errors in misspellings, typos, punctuation, grammar, spacing, links, and anything else that caught my eye without getting too anal about it.
