### ISSUE TITLE
Need BOF schedule

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#175]
Every year we say we are going to add a BOF schedule and every year it gets dropped. 

Can't we just clone the session schedule and set it to filter on session type = BOF ?

**Comment by esod** [comment]
There is a COD BoF Session features module. Up for giving it a try?

**Comment by esod** [comment]
COD BoF announcement and discussions:
https://drupal.org/node/1208088
https://drupal.org/node/1034482

**Comment by ForestMars** [comment]
@esod++

**Comment by likewhoa** [comment]
This feature was introduced at admin/structure/features/cod_bof. Thanks @esod
