### ISSUE TITLE
Style REGISTER for Event button

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#179]
All event pages should have an appropriately styled "Register" button, prominently displayed for a user to click to RSVP for the event. 

Currently the register button is just an unstyled link sitting next to the "view" link/tab, which most users won't even know what that is for. 

Solution: Please style the Register button so that it looks nice (the mixins for this are pretty standard) and improve its positioning on the page. It would be even better if the "view" link were hidden on the view page, bc the way it is currently styled makes no sense. 

Here's an example page: http://www.nyccamp.org/event/beginning-drupal-training-2014

**Comment by likewhoa** [comment]
We can't really re-position any tab items without ugly css hacks, my suggestion is to just style it so that it sticks out from the rest of the tabs or remove both tab items and instead add the register form in a block on those nodes.

**Comment by likewhoa** [comment]
@ForestMars Should be close this now since registration are almost going to be close and or should we just take care of this site enhancement after camp?

**Comment by ForestMars** [comment]
We're still getting a lot of feedback that the site UX is nigh unusable. 

In fact we just heard from someone today that said everyone in their organization went to the site but _"had no idea what to do."_

I don't know that this one issue is going to solve the UX problems on the site, but it's important to recognize where major improvements are needed.

**Comment by likewhoa** [comment]
For next year I think we should get rid of the 'register' tab menu link and instead have a register block and replace the current 'register for camp' block with a site menu link that points to a node that way we separate conference registrations with events registrations, so that the UX is less confusing.

**Comment by likewhoa** [comment]
don't think this issue is relevant now. Next year we should tackle the UX better and ahead of time.

**Comment by ForestMars** [comment]
The plan is to rebuild our distro on COD beta as soon as it's released (imminently.) 

Our immediate next step is to document all the changes we made to COD alpha-5. We should have a working group meeting about this at the next meetup so that it's ready for Drupalcon Austin @likewhoa @esod @scottrigby @willykaram
