### ISSUE TITLE
Training page is not working 

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#185]
The training page is coming up blank: 
http://www.nyccamp.org/training

Instead of having a view of all trainings for Training Day. 
cf. http://2013.nyccamp.org/training

**Comment by ForestMars** [comment]
Just to note that /trainings is the system path, and /training is an alias.

**Comment by likewhoa** [comment]
@ForestMars reason it's coming up empty is a filter on a non-existing content type called training, Also we might have to add a date filter so only this years content shows up from event nodes.

**Comment by ForestMars** [comment]
For this year it should filter on event node type, where field_session_type (aka "other info") is set to training. 

For next year we can revisit the data model.

**Comment by likewhoa** [comment]
it's filtering on event type now, it was on both event and non-existing training content type. let me look at field_session_type

**Comment by likewhoa** [comment]
This should be fixed now, open if otherwise.
