### ISSUE TITLE
/summits page is 403 for anon users

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#187]
For some reason, the basic page at node/114 is 403'd for anon users. 

This node has the aliases /summits and /2014/summits. 

I don't think this is related to OG bc it was returning a 403 _before_ it was posted into a group- in fact before basic page was even a group content type.

**Comment by likewhoa** [comment]
fixed, someone unpublished the damn node.

**Comment by ForestMars** [comment]
I won't pause to wonder how that got unpublished, but only note that we did uncover the oddity that /trainings is a view and /summits is a node. So that's an inconsistency that we should clean up in the next go round. 

Specifically, we should convert any remaining nodes to views, so that /summits is a permanent redirect to the dynamic view [current-year]/summits, which returns all events of type summit that are posted into the conference node for [current-year].  (The global text header for that page display should contain the "What's a Summit?" blurbage,)
