### ISSUE TITLE
Add Rules for Summit Sessions and BOFs

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#194]
As much as it pains us to decline sessions, we've added a new session status called "BOF" which should send out an email letting them know that we didn't have room in the main schedule, but that we really liked the idea and encourage them to do it as a BOF (later, we'll wire it up so setting a session to that status adds it to the BOF schedule, and alerts them that they can change the time to any slot available, as per COD functionality.)

To be clear, the essential differences between BOFs and scheduled sessions are: 
1. BOFs are not scheduled to be recorded using the DA media kits
2. BOF rooms tend to be smaller
3. BOF presenters are allowed to change the time & room to any other time or room that is available!

This ticket is to clone to existing _send email when session is accepted_ rule to make 2 new rules: 1 for BOFs and 1 for summit sessions, which use a different wording in the outgoing email, obviously. To be clear, these rules just check the session status field, which may be set to "accepted", "bof" "summit session" or "pending", "unprocessed" or "declined".

This would probably be a good ticket for a novice team member to execute.

**Comment by likewhoa** [comment]
the work I have already done on #202 can be extended to trigger on 'pending, unprocesses and or declined' sessions. This issue should be close and a new one added to archive what each one of these triggers will say.

**Comment by ForestMars** [comment]
As noted in irc, totes trust you nailed this, will test tomorrow.

**Comment by esod** [comment]
Do we want to include the additional statuses like bot, summit sessions in My schedules and My events?

**Comment by likewhoa** [comment]
@esod the roadmap would be to remove 'bof,training and summit' from field_accepted since those can already be reference in field_session_other_info and used as rules actions when a session is either accepted,pending or declined.

**Comment by likewhoa** [comment]
I am going to go ahead and migrate the new rule so we can close this issue now. Please open a new issue if you want to add more actions based on other field_accepted values.

**Comment by ForestMars** [comment]
Was this ever tested? As far as I can tell this is no longer working since the rules were combined into 1.  I also just took a peek at the code being used, and it actually doesn't look like it _should_ be working. Not a priority at all for between now and the camp, but reopening for post-camp regression fixes.

**Comment by likewhoa** [comment]
@ForestMars I tested this well and if it's not working now I will find out why in a bit.

**Comment by ForestMars** [comment]
Example of session node this did not work on: http://www.nyccamp.org/session/how-collaboratively-develop-product-drupal-community

**Comment by likewhoa** [comment]
This is because field_accepted should NOT have anything like 'summit session,BoF or training session'. The field should only be used to tell if a session was either accepted,declined or pending.

On that particular node the 'summit session' value should have been selected at field_session_other_info instead.

**Comment by ForestMars** [comment]
Why do you say that? (Are you saying that you believe 'pending' status is in COD?)

Need a specific reason here why you think additional status types are a bad thing and why those 3 are somehow magic.. Also, did you just know come to this conclusion? bc I could be mistaken, but I thought you were the one that originally combined the rules? 

NB. This was working fine before the rules were combined, so saying it that field should only contain 1 of those 3 fields can't be tied to the immediate issue, but needs a more detailed explanation explaining how it relates to previously working functionality. 

Or more to the point, a solution for meeting the requirements- to be able to for any proposed session , decide whether to: 

Accept it
Decline it
Recommend it for a summit
Suggest it as a BoF

And of course our friend event-vs-session is hiding in the accept-as-training status.

**Comment by likewhoa** [comment]
Pending is fine but the point of field_accepted is to know if a sessions is either 'unprocessed,pending,accepted or declined', not that it's part of a 'training,summit and or BoF' because we can already tell that by looking at the field_session_other_info which has training,summit and BoF as a value and the rule actually looks at these to determent which email to send out.

I didn't say that pending wasn't in COD but the values for training,summit and BoF were added by us and I thought that it was a mistake since it duplicates what was in field_session_other_info but whoever did that was just going by what the original rule was doing which was looking at field_accepted for the value 'accepted' to trigger the email.

**Comment by ForestMars** [comment]
We should start documenting our data model (ie outside of COD) before the next meetup. I agree that from a data modeling point of view we should avoid duplication such as having 'summit' and 'bof' both in 'type of session' and 'session status.'

This was somewhat unavoidable this year, but we should have a clean data model to use going forward. @likewhoa @esod @scottrigby @willykaram
