### ISSUE TITLE
Conditional fields

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#195]
Was surprised, given how many modules _are_ installed in the current profile, that we don't have conditional_fields module, especially given that multi-year, multi-event is somewhat complicated, and we are using the event bundle for summits, sprints and trainings. 

To make the best use of a single node as a polymorphous data type for all 3 of those main sub-types (as well as the other sub-types listed in field_event_type, we should install conditional fields module.

**Comment by likewhoa** [comment]
we do have it @ForestMars and it came with cod.

**Comment by ForestMars** [comment]
Ah that makes sense, I didn't look in the profile.
