### ISSUE TITLE
Facilitator field broken on Events

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#197]
For example on http://www.nyccamp.org/2014/training/git-training

Try to add Fureigh as the facilitator. 

This field seems to be working for Session node types, but not for Event node types.

**Comment by tz-earl** [comment]
http://www.nyccamp.org/admin/structure/types/manage/event/fields/field_speakers
ENTITY SELECTION > Mode > "Views:Filter by an entity reference view"

whereas in

http://www.nyccamp.org/admin/structure/types/manage/session/fields/field_presenters
ENTITY SELECTION > Mode > "Simple (with optional filter by bundle)"

**Comment by esod** [comment]
Good eye, Earl. The field should be set to simple. I've made the adjustment and added @fureigh as a facilitator to git training.

This issue ties in to the larger issue of how some of the field structures were altered in COD this year in a way that makes them kind of inflexible for our team and workflow.
