### ISSUE TITLE
User on live site has major bug

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#203]
As per the email I sent around, we have a user issue on the site which indicates a potentially major problem. 

A user (Rob) forwarded us their account creation email (from 3/3/14) which indicates they are uid 1301. However, they are somehow no longer that user-- and that uid now belongs to a different user! (Ed)

http://www.nyccamp.org/user/1310

Obviously, this is a major breakage, and while it seems like an isolated incident, we should investigate to determine the root cause. 

Note that Rob had also submitted a session, which also seems to have vanished.

**Comment by likewhoa** [comment]
yes, this was a side effect of the March 3th db disaster.
