### ISSUE TITLE
Add aliases for Summit Registration 

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#204]
We need to have nice urls to share to register for events. Currently however it's just the system path that's being used. For example, the DevOps summit registration link is: 

http://www.nyccamp.org/node/549/register

It should really have an alias such as: 

http://www.nyccamp.org/summit/devops/register. 

This should be the same for all trainings, summits & sprints.

**Comment by likewhoa** [comment]
All done,.. A few notes below.

2014/trainings/openshift-training (empty needs content description)

_no registration link for the below nodes:_
*http://www.nyccamp.org/2014/trainings/get-started-drupal
*http://www.nyccamp.org/session/drupal-content-creators
*http://www.nyccamp.org/session/thinking-drupal
*http://www.nyccamp.org/summit/security-summit
*http://www.nyccamp.org/2014/summit/drupal-core-summit
*http://www.nyccamp.org/event/d8-core-sprint
*http://www.nyccamp.org/2014/sprint/multilingual-sprint
*http://www.nyccamp.org/event/drupalng-sprint
*http://www.nyccamp.org/2014/security-sprint
*http://www.nyccamp.org/event/community-tools-workshop

_no 2014 style urls:_
*http://www.nyccamp.org/event/responsive-design-training-2014
*http://www.nyccamp.org/session/thinking-drupal
*http://www.nyccamp.org/summit/apps-startup-summit-2014
*http://www.nyccamp.org/event/npo-ngo-summit-2014
*http://www.nyccamp.org/summit/devops
*http://www.nyccamp.org/summit/higher-education-summit
*http://www.nyccamp.org/event/community-tools-workshop
*http://www.nyccamp.org/event/drupalng-sprint
*http://www.nyccamp.org/event/d8-core-sprint
*http://www.nyccamp.org/summit/security-summit
*http://www.nyccamp.org/session/drupal-content-creators
*http://www.nyccamp.org/session/thinking-drupal

I see we now have a proper url pattern for event content types and some others, but we need to regenerate these path aliases in order for these changes to take effect.
