### ISSUE TITLE
Input filter stripping header tags and maybe more

### ISSUE THREAD

**Issue by ElijahLynn** [NYC-Camp/website#223]
Somehow the input filter just started stripping header tags `<h2>` etc. My session was working fine the other day but a wyiwyg just got added and it seems something got broken. Does anyone know more about this?

http://www.nyccamp.org/2014/trainings/site-building

**Comment by likewhoa** [comment]
The problem here is that the 'Filtered HTML' format filter doesn't include the h2 tag. I will add this on that format so that you don't have to use 'Full HTML' which is overkill for your content.

**Comment by ElijahLynn** [comment]
Awesome, thanks!

**Comment by ElijahLynn** [comment]
It appears this got changed back. Does anyone know if this was intentional? I have admin rights now so I could change it back but don't know what is all going on right now.

**Comment by ElijahLynn** [comment]
Or maybe it is in a Feature and needs to be changed there?

**Comment by esod** [comment]
@ElijahLynn. There's too much activity on the site right now, too many modules being added, too many changes being made in the admin to keep the features up to date. Go ahead and add it back in the admin if you haven't already.

**Comment by ElijahLynn** [comment]
I set the input filter to full html for now.

**Comment by ElijahLynn** [comment]
I should also note that the original h2 tags that were there were turned into p tags somehow.
