### ISSUE TITLE
Unable to view camp schedule on mobile

### ISSUE THREAD

**Issue by jonpugh** [NYC-Camp/website#228]
Hey all,
Great work so far.

I was just checking the site on my nexus 7 to see what the day to day schedule was, but there's now way to see it! 

Something about the responsiveness is hiding it.

Wasn't sure if anyone knows, so I figured I'd file an issue.

Thanks!

**Comment by esod** [comment]
Hi @jonpugh Will you include a link?

**Comment by jonpugh** [comment]
Hey! Sorry, it's the front page. http://nyccamp.org.  Couldn't find a subpage with the info.

**Comment by jonpugh** [comment]
![screenshot_2014-03-30-19-30-38](https://cloud.githubusercontent.com/assets/106420/2562905/7059d2c2-b867-11e3-8a80-a82a2f214fef.png)

**Comment by likewhoa** [comment]
@jonpugh I don't even think we have a schedules link ready yet, at least from looking at the front page. I think they are still working on that atm.

**Comment by jonpugh** [comment]
Sorry, I wasn't talking about the session schedule. I am talking about the black sidebar with the overall day by day schedule. Thursday/trainings, Friday...?  Can't remember. Would be nice to check it on my phone!

**Comment by jonpugh** [comment]
The entire left column disappears if the screen is narrow enough, which means the block with all of that really useful information is not available at all on anything smaller than a desktop.

This seems like a critical issue to me, since that info is probably one of the most important pieces of the site.

![screenshot from 2014-04-03 09 53 07](https://cloud.githubusercontent.com/assets/106420/2604127/6b421a1a-bb37-11e3-9575-be4fc63e82ae.png)

**Comment by esod** [comment]
Looks like 768px is the breakpoint. On screens smaller than 768px the user sees a version of the main menu. I agree that this not too good.

**Comment by mirie** [comment]
There should be 2 icons in the upper right: one that looks like a calendar and the hamburger one. The calendar icon should display that general event blue sidebar. Is this what you're referring to?

**Comment by jonpugh** [comment]
Ohhhh I see.... I think that button wasn't working for me before...

Its not terribly clear that's what it does... Thanks for clearing that up,
@mirie

**Comment by likewhoa** [comment]
closing @jonpugh
