### ISSUE TITLE
Missing User Profile Photos

### ISSUE THREAD

**Issue by willykaram** [NYC-Camp/website#235]
User's profile photos are missing. The file are still on the server, it's just that the field is not retaining the settings. This appears to an issue relating to user profiles. For an example of discussion of a similar issue see: https://drupal.org/node/935592. The profile photos are still be saved on servers it's simple an issue of the settings for the field in the DB not being saved. We'll need to work to resolve this. I'm doing some testing locally to find a fix, but others are welcome to assist/try to take care of this too.

**Comment by tz-earl** [comment]
I can confirm that after reloading my photo just now on the My Profile page, click Save, navigate away, and then return to My Profile, the photo does not display.  In that sense, it may be a different issue from https://drupal.org/node/935592 which is about the photo disappearing after a user has been edited, either manually or programmatically. 

When I looked at the Featured Attendees page  http://www.nyccamp.org/attendees/featured  late last night, there was one photo displayed. All the others were missing.

**Comment by esod** [comment]
This issue may be a result of some bad play between Gravatar and Display suite. On your local if you, at minimum, set the Display suite layout for the User to none, the picture disappearing issue goes away when you add a new picture. But you have to add a new picture. So the damage is real.

So we'll have to fix this directly on the database.

**Comment by willykaram** [comment]
I think that Gravatar is at least part of the issue, as this hasn't worked properly from the outset. Anytime someone had been using Gravatar their profile picture wasn't displaying properly on the site in most cases that I saw.

**Comment by tz-earl** [comment]
FYI, on the live site, unchecking the Gravatar option for my profile does not fix the problem. After uploading a photo and Saving, merely navigating away and back to the profile page still causes the photo to disappear. 

I keep getting "You have updated your settings in NYC Camp 14 Email List." at the top of the profile page even when I haven't changed anything.

**Comment by ForestMars** [comment]
Has anyone checked Rules, just so we can rule that out.

Also, is this issue reproducible locally with the latest code and database?

**Comment by esod** [comment]
I haven't checked rules.

I have livedb and live files on my local. I confirm the bug on my local.

When I disable gravatar on my local, the picture stops disappearing. However, the link to the existing picture is not restored.

**Comment by ForestMars** [comment]
That's good news @esod. While I don't know why this would be a problem this year when it wasn't an issue last year, I don't think we really need gravatar. We really should just make profile pics required.

Can we confirm on Test please?

**Comment by esod** [comment]
I was testing on test on last night so it's kind of a mess. This morning I realized I could move the files to my local.

I'll put test back to a mirror copy of live.

Are you suggesting we disable gravatar and tell attendees to add their pictures again? I'm just asking.

**Comment by esod** [comment]
Test site is a mirror copy of live. I have disabled gravatar and added a new picture for myself. My picture is not disappearing.

On the upside, there are only 288 images in /Users/esod/kalabox/www/nyccamp2014/sites/default/files/pictures/ on my local. The file names have names like picture-1592-1395890676.jpg, who is user 1592. This means someone could go to http://test-nyccamp2014.gotpantheon.com/user/1592/edit and add back Thoka
Alowaid picture, picture-1592-1395890676.jpg. Which I just did.

I'd like to solve this issue from the broken connection in the database, but someone could go in and reset the images for the featured attendees to repair the front page carousel, for instance.

But before we disable Gravatar on the live site, will someone make another test on the test site?

**Comment by ForestMars** [comment]
Yes exactly, we should disable gravatar, confirm that the user profile picture is still set to be a required field, and in our next email blast to attendees ask them to make sure they have uploaded their profile pic.

Once we confirm disabling gravatar on Test resolves the issue, let's do it on Live.

**Comment by ForestMars** [comment]
While such diligence and looking for a confirmation is appreciated, if you disabled on Test and the problem goes away, I think that's sufficient to change on Live.

**Comment by esod** [comment]
Got it. It's fine on test. I'll implement on live

**Comment by ForestMars** [comment]
Earl,

As per Eric's Github update, after he makes the configuration change, can
you reset each of the featured attendees' profiles so their pictures show
up again?

**Comment by esod** [comment]
I'm doing the featured attendees, but if you see one @tz-earl, dive in

**Comment by tz-earl** [comment]
@esod @ForestMars I have dentist and other appts today, but if there's no super hurry with the non-featured attendees, I'll be glad to restore their photos.

**Comment by esod** [comment]
That's great @tz-earl thanks. 

All the featured attendees images are back in place. Their user profiles have their pictures, and their sessions have their pictures.

**Comment by likewhoa** [comment]
great work @esod, not even sure why we even worried about gravatars in the first place. @esod did you have to reupload the images? if so, that's gonna be a PITA.

**Comment by esod** [comment]
Is there a reason why http://www.nyccamp.org/session/drupal-8-challenges-ahead has Comments turned off? I'm just asking.

Except for the rooms it does look like the gentleman's session is listed twice. Why is that?

**Comment by tz-earl** [comment]
@esod @ForestMars I've re-uploaded a few photos from my local system. Will resume later this evening unless I hear otherwise from you guys. Gotta run.

**Comment by esod** [comment]
oh yeah @likewhoa uploaded the images manually. I first downloaded them from test:

https://dashboard.getpantheon.com/sites/a1afbb9f-3cbb-4fe0-22f8-7da39984db4c#test/backups/backup-log

and went through the list of user ids and matched the images. pretty much a pain, yes.

**Comment by likewhoa** [comment]
So I got a simple way to restore all user images which are missing but would require bringing the site down for 5mins or less.

**Comment by likewhoa** [comment]
@willykaram as I said on #236 and to respond to your question about bringing site down. It should be possible to do the comparison but my way would have been done much faster as I was just going to do a direct sync from old users db to new but only replace the picture values, but if you want to code something for this which I won't have time for tonight or anytime this week at least until I become active again beginning this weekend, then go right ahead. I was just pointing out the path to fix this issue.

**Comment by esod** [comment]
I've manually add about 100 photos in about a half an hour while I've got the television on. I'll have the 288 photos which were the contents of default/files/pictures on live as of Monday night reloaded in another few minutes. 

We can still run the script once it's ready. That's the best most scalable solution. But It doesn't need to be a blocker for a few hundred photos.

**Comment by ForestMars** [comment]
![Hard way](https://i.chzbgr.com/maxW500/1732036864/hBBC55FC7/)

**Comment by esod** [comment]
![hugemanatee](https://cloud.githubusercontent.com/assets/387576/2587387/9163250a-ba1e-11e3-930d-20f61592d71a.png)

all done

**Comment by mirie** [comment]
lol. :raised_hands:

**Comment by likewhoa** [comment]
lol @ForestMars and ++ to @esod

**Comment by likewhoa** [comment]
closing and opening a new issue w.r.t gravatar issue which introduced this fuck up.
