### ISSUE TITLE
Normalize Page Titles on User pages

### ISSUE THREAD

**Issue by esod** [NYC-Camp/website#247]
For anonymous users who are logging in:

The page title for user/login is Home
The page title for user is My Sessions
The page title for user/register is Home
The page title for user/password is User Account

Let's change them to:
Log in
Log in
Create new account
Request new password

respectively.

Pull request to follow momentarily.

**Comment by esod** [comment]
https://github.com/NYC-Camp/website/pull/248

**Comment by likewhoa** [comment]
gj!
