### ISSUE TITLE
Turning caching on for the various views

### ISSUE THREAD

**Issue by mirie** [NYC-Camp/website#252]
I'm adding this so we can all be on the same page here.

We have 110 enabled views (yes, I understand there are definitely duplicates here and no, I have no idea what's actually being used so I'm not going to waste time on that right now).

What's more critical is that for all 110 enabled views, there's no caching of the rendered output and no caching of the query results. I'm updating these right now.

**Comment by seantwalsh** [comment]
Updated the training Page and Block view!

**Comment by mirie** [comment]
ok, done and closing this out. anyone can adjust the views caching times appropriately as they please. This will at least help out with the zero caching on everything view related.
