### ISSUE TITLE
jquery_ui.module makes the ckeditor.module unresponsive

### ISSUE THREAD

**Issue by esod** [NYC-Camp/website#254]
Our trainers are seeing things like this:

![jquery_ui-makes-the-ckeditor module-unresponsive](https://cloud.githubusercontent.com/assets/387576/2617176/62b0bc48-bc0f-11e3-87da-b3e594c6a27a.png)

COD uses CK Editor, not Wysiwyg. Having both modules enabled was causing odd UX's like printing the body field twice. So we've disabled Wysiwyg. COD is too embedded with CK Editor to remove it easily so CK Editor is the one to go with. Now we can improve CK editor by getting rid of some of those buttons (see screen shot) but not until we disable jquery_ui. We need jquery_update.

I know this sounds confusing but it's not. What I need is for anyone who knows they are using jquery_ui to let me know. jquery_ui module is not required by anythingI think it can safely be disabled, which will permit us to modify the CK editor. 

Please let me know.

**Comment by esod** [comment]
I went ahead with these changes. I couldn't stand the idea of our users suffering through that interface any longer. It looks like this now:

![fixed-up-user-edit-screens](https://cloud.githubusercontent.com/assets/387576/2621609/740573d8-bc5c-11e3-910d-30030b32c256.png)

**Comment by esod** [comment]
And yes, these changes should be in configuration code.

**Comment by ForestMars** [comment]
Is this closable?

**Comment by esod** [comment]
Merge my pull request ( https://github.com/NYC-Camp/website/pull/276 ) and sure, let's close it.
