### ISSUE TITLE
Formatting of Event Facilitators Field

### ISSUE THREAD

**Issue by willykaram** [NYC-Camp/website#266]
We' need to format the facilitators on the events page, currently the images are too large, and inconsistent with the other theming on that page. We should likely set it to a similar format to the avatars lower on the page (which used a DS layout called "schedule"). An example where it needs to be improved is the NPO summit: 

http://www.nyccamp.org/event/npo-ngo-summit-2014

**Comment by willykaram** [comment]
Sorry didn't see @esod's #265 we can close or just address both

**Comment by likewhoa** [comment]
actualy molly started that one @willykaram
