### ISSUE TITLE
Adding a Food Page to the Site

### ISSUE THREAD

**Issue by willykaram** [NYC-Camp/website#272]
We need to have a page on the web site that explains the plan for food over the course of the conference. 

In particular the Cafe's in the Northlawn building, on Thu/Fri for coffee refreshments. The main Cafeteria on the ground level of the secretariat building, and the food/refreshments that we'll be providing on the 15th floor of the secretariat building. 

This document has some useful information in it: http://unstats.un.org/unsd/statcom/doc12/Note-NY-ResourceGuide.pdf

Janell has a good overview of this portion of the conference, so she can help with the copy/content for this page.

**Comment by postsimian** [comment]
sure, i can write content for web site

**Comment by postsimian** [comment]
The UN has some restrictions on where catering can be provided. Therefore on Thursday and Friday, we'll only be providing coffee and refreshments in the Secretariat Building, 15th Floor. For participants in the North Lawn Building, Cafe Austria on the 2nd Floor will be open for business between 8 a.m. and 6 p.m. as well as the Cafeteria in the Secretariat Building, Ground Floor. 

On Saturday, morning refreshments, a light lunch, and dinner hors d'oeuvres will be offered in the North Lawn Building and the Conference Building, Delegates Dining Room (see Saturday schedule below). On Sunday, coffee and refreshments will be offered in the North Lawn Building.

Thursday - Training Day
North Lawn 2nd Floor: Cafe Austria
Secretariat Ground Floor: Cafeteria
Secretariat Building 15th and 27th Floor: Coffee/refreshments will be provided.

Friday - Summits
North Lawn 2nd Floor: Cafe Austria
Secretariat Ground Floor: Cafeteria
Secretariat Building 15th: Coffee/refreshments will be provided.
Evening Social - Tuttles @ 735 2nd Ave.btw 39th and 40th

Saturday - Sessions
8 a.m. - Breakfast
    North Lawn 1st Floor: Coffee/refreshments will be provided
12 noon - Lunch 
    North Lawn: Light lunch will be provided
5:30-6:00 pm - Job Fair, Social/Drinks
        North Lawn Commons
6-6:45 p.m - Dinner hors d'oeuvres
        Conference Building Delegates Dining Room
6:45-7:15 Robin’s keynote
        Conference Building Delegates Dining Room
7-15-7:45 Closing remarks
        Conference Building Delegates Dining Room
9 p.m - Evening Social - Overlook @ 225 East 44th St.

Sunday - Sprint
    North Lawn 2nd Floor: Coffee/refreshments will be provided.

**Comment by mirie** [comment]
http://www.nyccamp.org/food and linked in the menu under About

**Comment by willykaram** [comment]
Thanks @postsimian totally appreciate you taking care of this. Once you're ready we can create a view that links to the notes with schedule/location details too, such as:

Sat night: : http://www.nyccamp.org/schedule/food-and-drinks

Thu/Fri Lunch: http://www.nyccamp.org/lunch-un-cafeteria
