### ISSUE TITLE
Can't run updates table missing (cache_panels)

### ISSUE THREAD

**Issue by robbiethegeek** [NYC-Camp/website#33]
Seems like the cache_panels table is missing it is added by : 
 function panels_update_7303() {
   $table_name = 'cache_panels';
   if (!db_table_exists($table_name)) {
     $schema = drupal_get_schema_unprocessed('system', 'cache');
     db_create_table($table_name, $schema);
   }
 }

WD php: PDOException: SQLSTATE[42S02]: Base table or view not found: [error]
1146 Table 'nyccamp2014_kala.cache_panels' doesn't exist: TRUNCATE
{cache_panels} ; Array
(
)
 in cache_clear_all() (line 163 of
/var/www/nyccamp2014/includes/cache.inc).
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;nyccamp2014_kala.cache_panels&#039; doesn&#039;t exist: TRUNCATE {cache_panels} ; Array
(
)
 in cache_clear_all() (line 163 of /var/www/nyccamp2014/includes/cache.inc).
Drush command terminated abnormally due to an unrecoverable error.   [error]

**Comment by esod** [comment]
Interesting. All's well for my localhost and our shared environments

vagrant@kala:/var/www/nyccamp2014$ drush @kalastack.nyccamp2014.kala updb
No database updates required                                                                               [success]
Finished performing updates.                                                                               [ok]

vagrant@kala:~$ drush @pantheon.nyccamp2014.dev updb
No database updates required                                           [success]
'all' cache was cleared in                                             [success]
/srv/bindings/8ec08cfb61f04b229afff05d4bbff049/code#dev.2014.nyccamp.org
Finished performing updates.                                                [ok]

vagrant@kala:~$ drush @pantheon.nyccamp2014.test updb
Warning: Permanently added '[appserver.test.a1afbb9f-3cbb-4fe0-22f8-7da39984db4c.drush.in]:2222,[173.203.36.165]:2222' (RSA) to the list of known hosts.
No database updates required                                           [success]
'all' cache was cleared in                                             [success]
/srv/bindings/4f9cb1ecbadd46e897398fd59bf649f9/code#www.test.2014.nyccamp.org
Finished performing updates.                                                [ok]

vagrant@kala:~$ drush @pantheon.nyccamp2014.live updb
No database updates required                                           [success]
'all' cache was cleared in                                             [success]
/srv/bindings/8e7c0d2cb508498abd6075f298318441/code#live.nyccamp.org
Finished performing updates.                                                [ok]

**Comment by robbiethegeek** [comment]
drush up is what I was looking at to update modules and then run updates.

**Comment by esod** [comment]
You may end up with modules in two places using drush with COD. COD has contrib modules in profiles/cod/modules/contrib and drush puts modules in sites/all/modules/contrib. 

There are no security updates currently needed for the site. I can have a look at updating panels, which is the one that I think is causing your PDO exception error. My plan, however, was to go with the existing code base as we are already in the development cycle of the site. Less any security updates that may come along.

The bugs that @ForestMars and @jmarkel have very recently uncovered seem pressing. Can we work on those. Do you have access to trello?

**Comment by mirie** [comment]
@esod @robbiethegeek, what's the status on this? Is this still an issue?

**Comment by esod** [comment]
No, this is not an issue.

Since we're considering removing OG from COD during the next several days, I don't want to update contrib modules at this time that are not a security update. The panels update from 7.x-3.3 to 7.x-3.4 is not a security update so this is not an issue.

**Comment by jonpugh** [comment]
Clearing caches on live does not produce an error. Closing!

**Comment by tutko** [comment]
https://www.drupal.org/node/2188277 

This is a known issue for panels updating from 3.3 to 3.4. The update commands are out of sequence, and update_7302() calls a table only created in update_7303()

There are several fixes offered in the Drupal issue cue I linked here. Number 34 works, as does a manual create of the missing table I used in Number 48. 

Good luck!
