### ISSUE TITLE
node/add/session broken for normal users

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#38]
Authenticated users cannot even save their titles as placeholders or whatever. When they click save they will be prompted with the error message:

You must select one or more groups for this content.

**Comment by ForestMars** [comment]
When an authenticated user goes to /node/add/session, they are presented with 2 fields: Session title, the vertical tab for "Revision information." 

All the other fields for session description, tracks, audience, length, "is training?", etc are all missing.

**Comment by mirie** [comment]
I think @ForestMars and @willykaram resolved this.

**Comment by ForestMars** [comment]
Y that's right.
