### ISSUE TITLE
Add Block for "Latest Slides"

### ISSUE THREAD

**Issue by mirie** [NYC-Camp/website#39]
This is for after the camp, when presenters are uploading their slides. Let's add a block display to a view showing latest slide uploads.

**Comment by ForestMars** [comment]
And tweet them as they go up!

**Comment by likewhoa** [comment]
@ForestMars doable with twitter module, rules and views_bulk_operations but you'll need to supply me with a test twitter account to abuse. In the meantime I'll add the latest slides blockz0r.

**Comment by likewhoa** [comment]
View is available at admin/structure/views/view/cod_session_sessions/edit now and will only show content with slides attached starting from January, 2014 at 4:20pm and on.

**Comment by mirie** [comment]
This looks good --

Would probably change the title to: Latest Session Slides and adjust the cache setting.

I know you have a filter set to unpublished for testing -- so I'm ignoring that -- just adding so that @ForestMars knows why its setup this way. 

Next time, you can probably setup your test nodes and import your view on Dev/Test (to verify what you have setup locally) and export the view when it's ready to go, and not have to worry about cleaning up your test nodes on Live and changing this kind of setting.

**Comment by likewhoa** [comment]
gotcha :smiley: 

block view is actually at admin/structure/views/view/sessions/edit/block_6

**Comment by jonpugh** [comment]
Set this to the milestone of camp day.  We don't need this until the day of the camp, so lets try and finish other issues first.

**Comment by likewhoa** [comment]
@ForestMars @mai please review this view so we can get this old issue closed. @jonpugh this is a minor feature and it's 99% finished so lets just get the remaining 1% done ;)

**Comment by ForestMars** [comment]
Will let @mirie take this for reasons mentioned on the #nyccamp channel

**Comment by mirie** [comment]
Discussed with @likewhoa using test sessions/block placed on front on Test.

This looks good. Only suggestion is to separate the (session + by presenter) using css. @likewhoa thinks it will be a good to change the session link so that it jumps down to the slide on the session node (html anchor). I think this is a great idea -- this would involve adding the id for the anchor since it doesn't currently exist on the node view. If that's too much, then I think it would be a good idea to at least increase the font size of the slides label and text so that they stand out better on the page.

**Comment by likewhoa** [comment]
c603db8 adds a html url id attribute for use as an archor link from the latest slides view. This uses theme_field();

**Comment by mirie** [comment]
Made changes to the view (on Live):

Under Format:
- Unformatted list - settings: unchecked the 2 options for classes. Added "session" for the Row class.
- Fields - settings: unchecked "Provide default field wrapper elements"

I noticed that the url for the session with the anchor was getting output with a double // like:
http://test-nyccamp2014.gotpantheon.com//session/content-migration-first-timers-impressions-and-lessons-learned#slide

so I configured the Path field to "Use absolute link" in the rewrite settings.

I changed the Presenters field:
- uses the label: "by"
- Uses: Customize field and label wrapper HTML -- Div
- rewrite from by `<em>[field_presenters]</em>` to `<em>[field_presenters]</em>`.

I added "latest-slides" to the CSS class setting for this block.

You can view the demo block on Test home (minus the adjusted styles) while it's still up. Please see pull request for style adjustment.

**Comment by mirie** [comment]
The pr was merged. Closing this out.
