### ISSUE TITLE
QA Task: Confirm that session acceptance emails are going out.

### ISSUE THREAD

**Issue by mirie** [NYC-Camp/website#40]
We need to either test this is working on Testing server, or, since it involves email, we could test on the live site by designating a session or 2 as test cases.

In any case, this absolutely needs to be confirmed working before sessions are accepted / finalized.

**Comment by ForestMars** [comment]
I think we still have a little bit of time on this. We can use a session submission by someone on the team as a test case.

**Comment by likewhoa** [comment]
I think this issue is resolved, please reopen if you feel it is not.
