### ISSUE TITLE
Checkin/Registration App to use with attendees arriving

### ISSUE THREAD

**Issue by mirie** [NYC-Camp/website#41]
Improvements on last years checkin/registration application.

**Comment by mirie** [comment]
@Offlein, please update this issue with the specifications so we can all be on the same page on the expectations. Can you also create a repo for this app?

**Comment by mirie** [comment]
Here's the repo link that @Offlein provided: https://github.com/NYC-Camp/nyc-reg2  Thanks!

**Comment by likewhoa** [comment]
Closing as we already have this forked, reopen if needed.
