### ISSUE TITLE
Clean out old roles of current users

### ISSUE THREAD

**Issue by mirie** [NYC-Camp/website#43]
We need to remove the additional roles (such as volunteer, session organizer, etc) from all of last year's user accounts.

Care should be made since updating a user will trigger adding the updated user to the mailchimp list for 2014.

I propose the following:
- [ ] Changing the MailChimp config (admin/config/services/mailchimp/lists/1/edit) from authenticated user to "Attendee"  (attendee already exists)
- [ ] Add the role Attendee to user accounts after successful registration
- [ ] Give the role Attendee to all user accounts that have recently (2014) accessed the site
- [x] Remove all of the additional roles from the old accounts

@rabellamy, did I capture what we discussed on Sat?

**Comment by tz-earl** [comment]
Is there any limit to the number of Attendees?

**Comment by mirie** [comment]
@tz-earl, sorry, what do you mean by limit?

**Comment by tz-earl** [comment]
@mirie Is there a cap on the number of people who are Attendees, a maximum number who, theoretically, might attend?

**Comment by mirie** [comment]
sure, I guess -- we can have only so many people at one time in the venue or in a given room. 

Anyways, looking at the current db, there's only one test account assigned the attendee role. I think the attendee role was never used

**Comment by ForestMars** [comment]
How are we distinguishing those who have an existing account on the site from those who are registering for NYC Camp 14? It sounds like we can do this with the attendee role, using rules, and synch that to a MC list for this year's attendees. #2xwin.

What other complications are involved with that, and does this put us on a bad path for next year's rinse & repeat?

**Comment by mirie** [comment]
We don't have any separation at this time for existing accounts vs new
registers besides the creation date.

I don't think it puts us on a bad path. However, we do need to do some
cleanup of the 2014 role assignments during the sunset for the site if we
are going to keep all of the users for next year.

**Comment by tz-earl** [comment]
If we're going to keep accumulating from year to year the set of attendees, maybe we need more granularity, e.g. "2013 Attendee", "2014 Attendee", etc.

**Comment by ForestMars** [comment]
What I meant was using the attendee roll to synchronize with MailChimp

The actual registration should be handled through organic groups of course

**Comment by mirie** [comment]
Ok, I updated old user accounts that haven't accessed the site for over 6 months and removed roles (volunteer, site admin, \* organizer, etc). Removed speaker roles from all accounts.

I didn't do anything with the Attendee role or the mailchimp settings. Closing this out.

Needed to finish this in order to handle #50.
