### ISSUE TITLE
QA - User profile form prompts users for "Organizer" info

### ISSUE THREAD

**Issue by jmarkel** [NYC-Camp/website#45]
On the fields for Phone number and Skype ID. Should be like "Please enter your [phone number | Skype Id] to be consistent with other fields on the form.

![organizer_instead_of_user](https://f.cloud.github.com/assets/3930383/2266296/11fa59b8-9e95-11e3-86eb-d58abaf22f4a.jpg)

**Comment by mirie** [comment]
@jmarkel 

I updated the help text on http://test-nyccamp2014.gotpantheon.com/. Are these okay? I left out the f/lname and Bio fields.

**Comment by jmarkel** [comment]
Looks good, Mai - let's go with that

**Comment by mirie** [comment]
Done.
