### ISSUE TITLE
Propose a Session - Presenters name

### ISSUE THREAD

**Issue by tz-earl** [NYC-Camp/website#46]
Edit Session form: I typed in my real name for the Presenters field. After that name was rejected, I realized it wanted my login username. 

After typing in the username, then the field also autofills the user id number after the username, eg. (55). That id number apparently is needed because if I edit out just the number and leave the username, the form is accepted but the field reverts to being blank.

Some words of explanation are called for.

**Comment by mirie** [comment]
@tz-earl,

I think this can be adjusted by doing the following: 
1. Go to /admin/structure/types/manage/session/fields/field_presenters/field-settings
2. Change the Entity Selection Mode to: _Views: Filter by an entity reference view_
3. Select: "cod_community_attendees - Entity Reference" -- this uses the admin/structure/views/view/cod_community_attendees/edit/entityreference_1 view

I made this change on http://test-nyccamp2014.gotpantheon.com/ -- Is this ok now?

**Comment by ForestMars** [comment]
@mirie's right, that should be using an entity reference to cod community view, however that's not going to hide those uid's for you. That's a bit of trickiness I'll wager is beyond our ken, given constraints. 

It does get us the ability to show user's profile pics in that entity reference view, which is probably not all that useful for this form, and not included in our FSD.

**Comment by mirie** [comment]
Yeah, the profile pics part is annoying. Is it ok to just override the view entity reference display?

**Comment by jonpugh** [comment]
User reference field sucks.  Usernames are unique. Why they need the `Name (uid)` display is beyond me.  We just have to deal with that.

the bigger problem is that the field is usually left empty by session submitters.

Can the reference view be set to default to the current users name so that new sessions have a "speaker" field value of the author?

**Comment by ForestMars** [comment]
Should we be editing the views that COD ships with, or cloning them and extending? 

Adding @scottrigby as we were discussing solutions to extending distribution features. Can we make this happen? 

@jonpugh First name / Last name are required fields. +1 for setting default value to current user. 

@mirie Profile pics are excluded from this display. Hoping that themers create a nice community page with user pics, however.

**Comment by esod** [comment]
+1 'the "speaker" field value of the author'. COD oob (out-of-the-box) autocompletes field_presenters with:

Mode
Views: Filter by an entity reference view
View used to select the entities
code_community_attendees - Entity Reference

This is too clever by half and we've already changed it on live to:

Mode
Simple (with optional filter by bundle)
Sort by
Don't sort

We must have made this change when resolving the node/add/session debacle (er, bug resolution).

The result is the Presenters field is empty by default. I think the Presenter field will often be overlooked by the person filling out the session form who I assume is the Presenter. <code>Name (uid)</code> is somewhat unpleasant to look at but not negatively impactful on the display side of the node. 

Using the assumption that the Presenter is the author, I will be modifying the Presenter field in the personal_schedule view to use the Content: author.

**Comment by esod** [comment]
Per using First and Last Names instead. Don't we like our usernames? Isn't that part of our scene?

The Drupalcon sites use usernames with presentations....

**Comment by scottrigby** [comment]
Every DrupalCon so many of us lament our d.o usernames aren't prominent
enough on the printed badges - I think the same can be said of some of the
camp websites. It can be a complicated issue... The reasons are many of us
know each other by username, irc nick (if different), and often last by
legal name (if we know that at all). Some prominent members of the
community don't like to list their legal name for privacy reasons (like
xjm). Personally I'd like to see both username and (only if volunteered)
"real name". Aside from all that, yes I agree we should try to find more
sustainable ways to extend COD, and I'm happy to help with the game plan
for that.

**Comment by mirie** [comment]
Ok, changed the field_presenters mode back to:

Views: Filter by an entity reference view
View used to select the entities
code_community_attendees - Entity Reference

on dev. Please review and if this is ok, then it's an easy configuration change on Live.

**Comment by ForestMars** [comment]
Hmm, I just tried to create a session and add presenters:

http://dev-nyccamp2014.gotpantheon.com/user/1303 (Barney Hanlon)
http://dev-nyccamp2014.gotpantheon.com/user/1302 (Craig Sinclair) 

and neither of them were found, no matter how I entered their name in the presenter field. 

Also, it doesn't look like it is actually searching by usernames, per above discussion, so searching for Crell returns nada,  but Larry Garfield is found. 

NB: These are 2 'different' issues- not working / not working right.

**Comment by mirie** [comment]
Looking at this view in greater detail, I discovered that we have OG membership as part of the filter category. Is this still a requirement?

I propose that we remove:
- OG membership: Group ID (in contextual filter)
- OG membership: OG membership from User  (in Relationships)
- OG membership state = Active (in Filter Criteria)

**Comment by ForestMars** [comment]
Does removing the membership fix the issue?

**Comment by mirie** [comment]
Closing this out. We already have users entering presenter names using their username -- it will be confusing to change it up at this point.

Instead I added some helper text: "Please enter the username(s)"

I also made this field required, as it doesn't make sense to have an empty Presenter especially since we are using this field for the Latest Slides block (not that the block display relies on it, but I believe our expectation is that we would have at least 1 Presenter per session).
