### ISSUE TITLE
Propose a Session - html in Description

### ISSUE THREAD

**Issue by tz-earl** [NYC-Camp/website#47]
Regardless of the choice of Text Format, it seems that all html markup is ignored and the Description text is always treated as plain text. For instance, the &lt;strong&gt; tag is displayed literally.

**Comment by mirie** [comment]
@tz-earl 

I can't replicate this. Here's the test session I created using tester_volunteer (authenticated role only) account: http://test-nyccamp2014.gotpantheon.com/session/test-session-markup

Are you using the wysiwyg buttons? If you want to add the html tags directly, you have to click _Disable rich-text_

Can you provide more detail on the steps you're taking so I can replicate this issue? Thanks!

**Comment by tz-earl** [comment]
@mirie I'm an idiot. Chalk this up to Operator Error. Of course, I now realize that the default text area is wysiwyg and that "Disable rich-text" = "Edit in HTML".
