### ISSUE TITLE
Propose a Session - <!--break--> in Description

### ISSUE THREAD

**Issue by tz-earl** [NYC-Camp/website#48]
Instructions for the Description mention that the delimiter &lt;!--break--&gt; can be used to indicate where the trimmed version splits off, but I haven't been able to get that delimiter to work. (See previous issue about html not being recognized.)

**Comment by mirie** [comment]
Hey @tz-earl, I'm looking for the text that says a user can use  

I'm seeing: 
Text Format   <dropdown>
Allowed HTML tags: <a> <em> <strong> <cite> <blockquote> <code> <ul> <ol> <li> <dl> <dt> <dd> <h4> <h5> <h6> <p> <br> <img> <strike>

Can you point me in the right direction?

**Comment by tz-earl** [comment]
@mirie If you go to the Edit Session page, eg.
  http://test-nyccamp2014.gotpantheon.com/node/528/edit
and click on the Preview button at the bottom, you'll then see at the top of the page

"The trimmed version of your post shows what your post looks like when promoted to the main page or when exported for syndication. You can insert the delimiter "" (without the quotes) to fine-tune where your post gets split."

But the preview of the trimmed version does not truncate the Description where the  was inserted.

**Comment by mirie** [comment]
Ok, this is not a big deal because we are going to decide on the teaser presentation, not the authenticated user.  I'm going to mark this as won't fix.
