### ISSUE TITLE
QA - Podcasts page - Duplicate page title

### ISSUE THREAD

**Issue by jmarkel** [NYC-Camp/website#52]
"Podcasts" appears both as an H1 and an H2, one above the other.

Looks like the Panel is putting in the duplicate header tag

**Comment by mirie** [comment]
@jmarkel,

This Panel can be edited here: admin/structure/pages/nojs/operation/page-podcasts/handlers/page_podcasts_panel_context/content

Steps taken on Variants > Content
1. Changed the "Title Type" to Manually Set and added "Podcasts"
2. Clicked the gear icon to the right of the Podcasts panel in the Intro section, and selected Settings from the context menu
3. Checked _Override title_ and set the title to blank.

I set this up on http://test-nyccamp2014.gotpantheon.com/. Can you check?

**Comment by jmarkel** [comment]
Fixed it this AM in test and in Live
