### ISSUE TITLE
Make default status of Status field Pending

### ISSUE THREAD

**Issue by esod** [NYC-Camp/website#54]
The default of the Status field (field_accepted) is set to None. A status of None prints nothing on the View. Let's change the default to Pending.

**Comment by mirie** [comment]
@esod, is this already setup on prod? I see you re-opened this.

**Comment by likewhoa** [comment]
Where is this view you speak of @esod?

**Comment by esod** [comment]
@likewhoa I mean View as in MVC View. I guess that's not precise enough in context.

I'll post a screenshot.

**Comment by esod** [comment]
@mirie I accidentally clicked closed. That was a slip of the hand only. 

Screen shot to follow will explain what I mean.

**Comment by esod** [comment]
![change-status-default-state-to-pending](https://f.cloud.github.com/assets/387576/2290940/7008cf7c-a02e-11e3-928d-2ebcf06b96e3.png)

**Comment by likewhoa** [comment]
all done.
