### ISSUE TITLE
The Twitter and Facebook blocks on the front page are empty

### ISSUE THREAD

**Issue by jmarkel** [NYC-Camp/website#56]

**Comment by likewhoa** [comment]
Where are you seeing this @jmarkel? WFM on live.

**Comment by jmarkel** [comment]
Seeing it (actually, NOT seeing it) on live (http://nyccamp.org) and on dev, test, and local

The Twitter block just has a link to the twitter account instead of showing a list of recent tweets as it should

**Comment by mirie** [comment]
@jmarkel,

I checked this out on nyccamp.org as:
- anon user
- authenticated user
- site admin user

In all cases, I see the content in the twitter and facebook blocks. This was in Chrome.

Can you provide browser details?

**Comment by tz-earl** [comment]
http://test-nyccamp2014.gotpantheon.com/

twitter and facebook blocks on the front page are well populated in Firefox 26.0, Chrome, and Opera Mini on my dumbphone.

**Comment by jmarkel** [comment]
Weird. Must be adblock or something. sigh

**Comment by jmarkel** [comment]
It was my "Disconnect" plugin. Sorry...
