### ISSUE TITLE
Create (or find) (or fix) View Sessions pages

### ISSUE THREAD

**Issue by jonpugh** [NYC-Camp/website#58]
We need one for "Submitted sessions" and "accepted sessions."

**Comment by jonpugh** [comment]
http://live-nyccamp2014.gotpantheon.com/admin/structure/views/view/nyccamp_schedule/edit

The view, for reference. Thanks, @esod

**Comment by mirie** [comment]
Hey there's this sessions view: admin/structure/views/view/sessions/edit

Is that what you're looking for?

**Comment by jonpugh** [comment]
Good question.  I'm not taking this on now, I just posted the issue because there wasn't one yet.

I was assuming that COD would have that page!

**Comment by jonpugh** [comment]
weird, I cannot label this issue...

**Comment by mirie** [comment]
That's very weird. I just labeled it.

**Comment by jonpugh** [comment]
I am not an admin of this repo, thats why i think.

Anyway the proposed sessions view was filtering on "Unprocessed", not pending.  Fixed: http://live-nyccamp2014.gotpantheon.com/program/sessions/proposed

**Comment by jonpugh** [comment]
TODO:
- [ ] Add more info like Track.
- [ ] Add exposed filter for track.
- [x] Add a menu link to the main nav and to the "Submit a session" block, and to the http://nyccamp.org/event/sessions-all-day-sat page.

**Comment by mirie** [comment]
Added you as a member.

**Comment by jonpugh** [comment]
thanks!

**Comment by jonpugh** [comment]
Should I ask for approval to add links to the proposed sessions page? or for forgiveness after I do it myself?

**Comment by jonpugh** [comment]
Done.  Link added under About menu, to frontpage session block, and to "All day sessions" event page.

**Comment by jonpugh** [comment]
Good enough for now.  Let's open another issue for enhancing down the road.
