### ISSUE TITLE
Create Sessions block in code, remove code in sessions block

### ISSUE THREAD

**Issue by jonpugh** [NYC-Camp/website#59]
I know its convenient, but we really should NOT use PHP Code input format in a block!

It is really not hard to use hook_block_info() and hook_block_view().

It is SO easy to break this... 

```
<p><?php
    if (user_is_anonymous()) {
        print '<div class="register-now">' . l(t('Register now to submit a session'), 'user/register') . '</div>';
    }
    if (!user_is_anonymous()) {
        print '<div class="register-now">' . l(t('Submit a Session'), 'node/add/session') . '</div>';
    }
?></p>
```

http://nyccamp.org/admin/structure/block/manage/block/8/configure

**Comment by likewhoa** [comment]
Yes, I agree and we should disable the php module all together as is is BAD practice to put code into the DB. All custom code should go into sites/all/modules/CUSTOM/... FFS.

**Comment by ForestMars** [comment]
1. JohnPugh++ for pointing this out.
2.  "really not hard to use hook_block_info() and hook_block_view()" So, @jonpugh, which commit did you push that in…?  :-p
3.  https://gist.github.com/ForestMars/9270323

**Comment by rabellamy** [comment]
ForestMars++
