### ISSUE TITLE
Review Pages

### ISSUE THREAD

**Issue by mirie** [NYC-Camp/website#63]
@willykaram or @ForestMars:

Reviewing: /admin/structure/pages

**Enabled but seem to be missing content**
- page-landing_page -- /landing -- /admin/structure/pages/edit/page-landing_page
- page-team -- /team -- admin/structure/pages/edit/page-team

**Disabled, but possibly relevant?**
- page-organizers   Organizers  /organizers
- page-accommodations   Accommodations  /accommodations
- page-food Food    /food
- page-program  Program /program
- page-featured_spealers    Featured Spealers   /featured-speakers
- page-sponsors Sponsors    /sponsors
- page-food_options_page    Food Options Page   /food-option-map
- page-events_dashboard Event Dashboard /node/%node/dashboard

For the list above, are we going to use any of these? If so, we will probably need new content as well, right?

**Comment by mirie** [comment]
Ok, sorry I accidentally created the issue description while I was still typing. Please see the revised description for the full question, properly formatted.

**Comment by jonpugh** [comment]
with the exception of sponsors and the event dashboard, I don't see why any of these exist as "page manager pages".

They should all just be "static page" nodes. They are all content.  Wipe them out to avoid confusion, but create some Static page nodes in their place and encourage someone to step up and start filling them out.

**Comment by mirie** [comment]
@jonpugh, yes, this came up in a discussion (a few times) back in November/December. The final decision was to continue using Panels. I would like to revisit removing Panels post-camp.

I'm guessing based on Forest's response to my question about the views, these will probably be used as well.

**Comment by mirie** [comment]
I'm closing this.
