### ISSUE TITLE
Tone down the language on Git Training page

### ISSUE THREAD

**Issue by jonpugh** [NYC-Camp/website#69]
> Use version control or Webchick will stab you.

I'm not sure webchick would appreciate people fearing her.  Also, if you aren't "in the club", you don't know who webchick is (which is probably a good portion of the people who are interested in git training.)  We can be clever and funny here without confusing and scaring people.

http://nyccamp.org/event/git-training

**Comment by ForestMars** [comment]
You also probably don't get the 'stab' reference, which is a pretty old trope in Drupal, and is probably lost on newer people. +1 for removing.

**Comment by esod** [comment]
Jesus, who wrote that copy? That nice lady's not going to stab anyone. I'm taking that line out immediately.

**Comment by ForestMars** [comment]
Well technically, Webchick wrote that. 

The fact that you don't know that only underscores the need to remove it, as I doubt that many other people would get the reference.

**Comment by esod** [comment]
I may have overreacted a bit when I saw that. Still, let's not say that.

**Comment by likewhoa** [comment]
i get it lulz. webchick++

**Comment by jonpugh** [comment]
I get it too.  It's funny in context, like at a session, from the actual mouth of our friendly happy webchick.  As bold copy on a stark text-only web page, it's...  intense.

We should present a friendly face!  

Thanks!
