### ISSUE TITLE
left-sidebar creating undesired blank space at bottom of page

### ISSUE THREAD

**Issue by ElijahLynn** [NYC-Camp/website#7]
![workspace 1_345](https://f.cloud.github.com/assets/1504756/2060726/8c1fa746-8c2c-11e3-9e7b-505f75904106.png)

Not quite sure why yet.

notes: padding-bottom: 100%, results in 2000 pixel bottom padding. Chrome 32 on Ubuntu

**Comment by Offlein** [comment]
is the element 2000px high? If so isn't that what 100% padding means? I may be wrong.

**Comment by ElijahLynn** [comment]
So far if I change padding to 51% it looks fine. Still setting up local environment though.

**Comment by ElijahLynn** [comment]
Interesting, according to CSS 2.1:

> **<percentage>**
> The percentage is calculated with respect to the width of the generated box's containing block, even for 'padding-top' and 'padding-bottom'. If the containing block's width depends on this element, then the resulting layout is undefined in CSS 2.1.

Source: http://www.w3.org/TR/CSS2/box.html#padding-properties

**Comment by mirie** [comment]
@ElijahLynn, can I assign this one to you? Are you all set with getting setup?

**Comment by ElijahLynn** [comment]
K, I am setup now. Does anyone have any background on where this theme came from? Was it custom/contrib?

**Comment by ElijahLynn** [comment]
@robbiethegeek

**Comment by ForestMars** [comment]
Zen Avenue? That's the theme Tim Hobert did for the camp last year, based on Zen, obviously.

**Comment by likewhoa** [comment]
@ElijahLynn I removed that crazy ass padding in #84, let me know if this looks better for you even though we probably will not use this theme for very long.

**Comment by mirie** [comment]
This is fixed from the last push of theming changes.
