### ISSUE TITLE
Create Partners Info page and block

### ISSUE THREAD

**Issue by jonpugh** [NYC-Camp/website#70]
There is currently nothing on the site for potential partners to find out more info.

Check out midcamps sponsor page for inspiration: http://2014.midcamp.org/sponsor-midcamp

**Comment by ForestMars** [comment]
Updated issue description (and @jonpugh's comment!) to say "partners" instead of "sponsors"

**Comment by mirie** [comment]
We already have this set up in Panel and located @ /sponsor (/admin/structure/pages/nojs/operation/page-sponsor_nyc_camp/handlers/page_sponsor_nyc_camp_panel_context/content) and there are 2 views for handling the output:
admin/structure/views/view/sponsorship_options_tiers/edit
/admin/structure/views/view/sponsorship_options_title/edit

**Comment by mirie** [comment]
@ForestMars  or @willykaram 

Other than changing the copy to replace "sponsor" with "partner" -- I think we're going to need to change the actual sponsorship options (due to signage restrictions, etc), right?

**Comment by ForestMars** [comment]
Yes, absolutely, and let's do this post-haste so as to not have any misinformation leaking out.

**Comment by willykaram** [comment]
Gang - Most of this is already done, we'll have it finished up today, see http://nyccamp.org/partner ... we're just refining the wording, pricing & packages today and it will all be sent to sponsors later today. Unfortunately this has been a moving target, and we made some pretty big strategic changes on Fri/Sat. that we're finishing up today. WRT individual partners, see: https://github.com/NYC-Camp/website/issues/115

**Comment by mirie** [comment]
@willykaram, can this link be exposed in the menu now?

**Comment by mirie** [comment]
Ok, I will have something ready for fixing the styles on the themeup branch/environment:
- All of the sponsor block views have been altered to use HTML list rather than the table grid.
- I also altered the Panel.

http://themeup-nyccamp2014.gotpantheon.com/partners

**Comment by likewhoa** [comment]
:+1:  @mirie looking good, wasn't the blocker on this? We should move this to live as the current partners page looks to cramped up.

**Comment by willykaram** [comment]
I haven't had time to review the PR. But it you guys think this is good to
go, it would be great to get this moved to live if it help to clean-up the
parters page.
