### ISSUE TITLE
Create more detailed venue info and directions page.

### ISSUE THREAD

**Issue by jonpugh** [NYC-Camp/website#71]
MidCamp's page is awesome. We should do better: http://2014.midcamp.org/directions

**Comment by ForestMars** [comment]
Their dates, however, are not. 

I'm none too happy having to choose between MidCamp and Drupal Dev Days.

**Comment by esod** [comment]
MidCamp's page is wonderful. Do we have a Directions page? Let's get on this.

**Comment by likewhoa** [comment]
I'll take this on tonight.

**Comment by likewhoa** [comment]
i was told to hold on this,.. so I will take myself from tasks and reassign myself when I am ready to get this done.

**Comment by mirie** [comment]
I've got the writeup locally with the map. I just have to finish up the driving instructions.

**Comment by mirie** [comment]
http://nyccamp.org/directions

**Comment by mirie** [comment]
Also added to the menu under About, right above Parking. The line-height for the h3 should be fixed by https://github.com/NYC-Camp/website/pull/149

**Comment by mirie** [comment]
#149 already merged. Closing this out.
