### ISSUE TITLE
Approach to Solving Permissions/Access Control Problem

### ISSUE THREAD

**Issue by willykaram** [NYC-Camp/website#76]
**Intro**

This issue is intended to outline our approach to addressing the problem that we've run into relating to permissions and our config OG/access controls.

Below this issue outlines: (1) Our interest in a multi-year strategy for the NYC Camp site in keeping with the COD roadmap, (2) A brief summary of the OG/access control problem that _we have seem to have created ourselves_ -- i.e., it's not a COD bug, (3) a suggested short-term '_band-aid_' solution of disabling the OG fields that doesn't compromise our longer term COD goals, and (4) a suggested longer term approach of debugging/resolving the problem and continuing to document things in manner that benefits COD, other Drupal camps and NYC Camp.

Apologies in advance for the long issue summary, I didn't have time to shorten it up.

**1. Commitment to Multi-Year COD Strategy** 

At the outset of the Camp planning last fall, there was some debate over wether to use COD. However, we reached a strong consensus that there are major benefits to continuing to use COD, and ideally implementing it's multi-year functionality so that we have less work to do each year (i.e., in keeping with the intended alpha COD release). We didn't have time to fully document our approach for multi-year implementation, but our goal is to to so for next year. For example, we need to decide and document:
- How to handle different themes year-to-year, and whether or now we want to preserve themes for prior years (typical of Camp sites) -- that said, we could simply agree on a theme/look that we use and evolve for several years;
- Our desired site building, content strategy and information architecture for a multi-year site (e.g,. navigating sessions and content, etc.); 
- Whether to want to export a flat/HTML archive of the site after each year's camp as well (as we have in past), or to simply rely on the live site (which would be more in keeping with the latest COD roadmap).

We should avoid diving into the above/strategy issue for now. However, I simply wanted to reiterate our agreed upon approach from last fall, and encourage the team not to revisit that here/now (that's not the the aim of this issue). As a team, we've been committed be being at the forefront of community efforts to help move COD and it's adoption forward -- we should stay the course (as Forest has articulated several times).

**2. Summary of our OG/Permissions Problem** 

To be clear this does not appear to be bug with the re-writes of COD or OG for D7. Unfortunately, in creating the new site for this 2014 we've run into some issues relating to permissions and use of Organic Groups. We know this because, after sorting our some initial issues, we used that COD distro and OG module last year without without encountering the issues that we have this year (that archive site is still accessible at http:2013.nyccamp.org if we need to test). So, it appears that the issue we've run into this year related to our configuration, and some potential conflicts among the permissions related modules that we're using (i.e., OG, Content Access and Field Permissions). Some symptoms of the issue are that anonymous users can access the /node/add page and create certain node types from there (an issue we didn't have with the codebase/database that we used as our starting point this year). These sorts of issues can easily be encountered if using multiple permissions-related modules that may not play well together (especially early in the release cycle). Simply put, it's not uncommon to run into precedence issues when using multiple modules that deal with node access. These issues can generally be avoided with some planning/bridge modules (https://drupal.org/project/domain_access_bridge), and can be debugged with some effort). In reviewing the issue on the 2014 site, the configuration in the database for some of the node type and fields appears to be identical; as such, the issue is most likely related the the modules not playing well together/precedence issues. It's tough to say but this could have arisen when configuring those modules, adjusting field permissions or perhaps rebuilding permissions. Regardless of how we arrived here, we're likely in need of a short term solution to keep things moving forward, and a long term solution to achieve our broader goals with COD. If we need to expand on the technical details of the problem, perhaps we can do so in the comments below (I haven't gone deeper here b/c I'm short on time, the issue is already super long, and I'm trying to stay focused on some other other aspects of the camp I'm working on -- i.e., FSD, venue, sponsorships, sprints, etc). 

**3. Suggested Short Term Solution** 

For immediate purposes of NYC Camp 2014, we're not using the multi-year functionality in the latest alpha release of COD that we're running (i.e., although the 2013 content is on the site, it's unpublished). As such, we can likely disable the OG functionality for now; and then re-enable it in a few weeks after the camp, or sooner if we have time to sort out the above configuration issue. This doesn't involve disabling or uninstalling OG. Rather, it simple involved disabling/removing some of the OG fields that we've installed (some of which we're done hastily last year). Making these changes should solve the current issue, and is something that both Eric and I tested, and which Eric has implemented on a MultiDev environment which others can use for further review/debugging (http://cod_sans_og-nyccamp2014.gotpantheon.com/). Given that the NYC Camp is only about 5-6 weeks, away we still have lots to do on the web site, and we don't have any immediate plans/need for the OG functionality. So there is some benefit in this quick fix approach, as long as it's documented along with the strategy for eventually resolving the problem and sticking with the above strategy outline above in (1). Since we're not hacking any OG Code, is should be quite easy to re-enable these fields as needed when we resolve the problem as outline in (4) below.

**4. Long Term Solution**

If we adopt the above quick fix solution, it's important that once time permits, we sort out the problem and ideally re-implement the OG fields/functionality. We can potentially do so before NYC Camp if team members have time to do so. However, so far we've spent a lot of time trying to sort out the problem without a clear solution. More importantly, this is pulling the dev team's time away for keep pressing issues, such as general theming, responsive theming, or (most importantly) working on the sessions grid and event schedule (which are must haves for the event). With that in mind, the long term solution, is to resolve this problem with a view to implementing the mutli-year COD functionality for 2015, effort which due to time constraints would most likely begin at a COD sprint at NYC Camp or once we resume work for 2015. This solution should allow us to achieve our goal of not needing to do a major rebuild of the NYC Camp site for 2015, and instead focus those efforts on initiatives such as creating a great responsive theme that eliminated the need for a native app, making sure we contribute our code/documentation back through CODify and/or COD Extras, and ideally create some resources that can be re-used by all Drupal Camps and (maybe even) DrupalCons that use COD. Again, if someone wants the can dive into this in the interim, but but we need to keep _everyone else_ on the team and the site on track for this year (having all hand working on this issue, like we did last Tues, isn't really an option again).

**Conclusion**

Simply said, right now we need to '_put first things first_'. While the above approach isn't ideal, it's pragmatic and reflect the limited resources/time we have. Frankly we need to get through this issue asap, and onto some of the high priority items ahead (e.g., sessions grid, theming, etc). We've made some great strides forward with our team, dev workflow and site efforts this year. Hopefully in the comments below we can agree on a solution along on these lines, and keep working towards a great camp (... COD FTW!!).

**Comment by esod** [comment]
https://github.com/NYC-Camp/website/pull/79

I like Organic Groups, but if we don't the functionality and the permission bugs are hurting us, this is a way forward.

**Comment by likewhoa** [comment]
lets deal with the permissions issues with our current hacks and try to figure out why og_field_permissions is mis-configured and or bugged instead of getting rid of OG all together since it worked last year.

**Comment by ForestMars** [comment]
I'm still having a bit of a time understanding the allusions to "removing organic groups" and why we are working on a branch called "cod sans og." 

As Willy's explanation of this issue should make abundantly clear, we are not going to be removing OG now or in the forseeable future. 

We have, however, proposed to remove a particular OG field that seems to be connected with the anonymous user bug. 

Does the cod-sans-og branch remove og altogether? Because that's not what is described above, and not the way forward. 

I feel  like there is a great deal of noise here over anonymous users being able to go to the node add page, and while that's obviously wrong, I'm not quite seeing what has made that into such a spanner in the development works. 

Given the urgency of the timeframe, also elaborated on in Willy's issue summation, can someone please add details on: 
1. If there is anything missing from the issue description at https://drupal.org/node/2205773
2. If og-sans-cod branch merely removes "the fields in question" or whether it goes further to remove OG from COD. 
3. Executing on removing "the fields in question" - isn't this like a 5 min change? Don't we also have proposed solutions (and PR's) from @jonpugh (using hook_menu_alter) and @likewhoa (using user_access)? 

Trying to cut through the noise to the signal here so we can get this patched up today.

**Comment by jmarkel** [comment]
True, Fernando, it used to work, but it doesn't now. We must have screwed
something up along the way.Time is short, so if we can live without the OG
functionality for now then we should do that and move to more pressing
things. When's there's some free time we can figure out what the OG issue
is. Too much time has been taken up with this already.

On Sun, Mar 2, 2014 at 1:42 PM, Fernando Reyes notifications@github.comwrote:

> lets deal with the permissions issues with our current hacks and try to
> figure out why og_field_permissions is mis-configured and or bugged instead
> of getting rid of OG all together since it worked last year.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/NYC-Camp/website/issues/76#issuecomment-36462193
> .

## 

Don't anthropomorphize computers - they really hate it when you do that.

**Comment by ForestMars** [comment]
@jmarkel - we need to be very clear here. Saying "live without the OG functionality" lends itself to 2 very different interpretations: 
1. Removing og fields that are causing anon users to be able to access node/add page
2. Removing (uninstalling) OG from the base install. 

#2 is not going to happen, it's #1 that's being discussed. 

As per my above comment, we also seem to have solutions for this from @jonpugh @likewhoa. Do we just need to pick one and execute so we can move on?

**Comment by jmarkel** [comment]
@ForestMars My concern here is that an awful lot of time, attention, and
effort has been and continues to be spent on this. Whatever gets us to at
least the minimal functionality we can live with, while not putting us in a
deeper hole later, is what we should do.

**Comment by ForestMars** [comment]
@jmarkel Exactly. We are completely on the same page here.

**Comment by likewhoa** [comment]
@jmarkel removing og is just clearly giving up on troubleshooting an issue which is not something I agree on, hence why we have 2 working hacks to workaround the issue **temporally**. :-1: on removing og as COD is heavily tight to it and if we want upstream to adopt our modified distribution of COD we should really not strip out functionality that it's part of it. That's just not how we do things.

We should decide now, and in a few minutes I will make a pr request for such a temporally fix which uses code that @jonpugh introduced. Lets stop wasting time and get it done so we can focus on more important matters i.e figuring out why og_field_permissions is not working properly and or other issues at hand.

**Comment by jmarkel** [comment]
@likewhoa Not disagreeing with you at all.

**Comment by likewhoa** [comment]
someone review and merge #80 so we can move on and focus on other issues but lets not forget why we are applying this _workaround_ ;)

**Comment by esod** [comment]
The node/add bug seems to be just one problem in many with OG in our stack. And we've developed three plausible workarounds for it.

We are talking about removing OG, or at least parts of it for the time being. I'm upping the ante by suggesting that we disable OG all together so it's out of our way. If we lose functionality as a result, that's important and a reason for us not to go in this direction. But we won't know unless we implement cod_sans_og on local/dev boxes and see if it works better.

@ForestMars I thought about what I said when I said that Drupal is not Photoshop. I think I like it  better to think that Drupal is not Adobe and COD is not Photoshop. We are working with open source tools that are still in development and we have to be pragmatic. If a tool is not working out for us, let's not use it.

**Comment by ForestMars** [comment]
> "The node/add bug seems to be just one problem in many with OG in our stack."

Ok look, we've asked for any problems that are blockers to be documented in an issue. The hand general hand-waiving at vague "problems" stops now. 

> "We are talking about removing OG, or at least parts of it for the time being."

No, not really. That is not an option. Please re-read this issue again (sorry, I know it's a long description); in particular, note where it says: 

> "This doesn't involve disabling or uninstalling OG. " 

I don't mean to be terse here, but all the hand-waving has nearly stalled development here, and create a LOT of noise. Bugs are to be filed as bugs. Problems are to be reported with steps on how to reproduce the problem. 

Again, sorry if this seems terse. The camp is 38 days away.

**Comment by esod** [comment]
I think the features modules which are at the core of the COD distribution are permanently broken. The modules became permanently broken as a result of the work we did to resolve the node/add/session bug late last Monday night. This is a blocker to new development. I was not able to move the session_attending flag configuration changes I made today up the stream because of this blocker. Features modules that are permanently broken are what @scottrigby and I are discussing. However, this is our current situation. 

The features modules in cod_sans_og are in Default. The sans og modules are duplicates of their originals except the og fields were left out.

**Comment by ForestMars** [comment]
> "I think the features modules which are at the core of the COD distribution are permanently broken." 

Then you should file this as a bug against COD, with steps to reproduce. 
https://drupal.org/node/add/project-issue/cod

> "The modules became permanently broken as a result of the work we did " 

That's different, but also unclear. Are you saying ALL the features modules are broken? Some of them? Broken how? What are the steps to reproduce? Again, this is all very hand-wavy and not terribly helpful. 

When I look at features-diff, I don't see anything broken, I just see normal features overrides. And overriding distribution features is exactly what we were discussing with @scottrigby at WDHH. In fact, it's being discussed a lot in Drupal, since it's a common pattern to need to extend features that are included with a distribution. 

If you have a solution for this problem, or indeed, any insights on how to mitigate it, please share with https://groups.drupal.org/distributions. 

Edit: Taking another look at the features overrides, it appears we are already overriding COD features;  so abstract/ideal discussions of distribution features put aside, it seems someone just needs to pull the db down to their local, run features-update, and push the modules back up with a PR. (Can someone verify this please?)

**Comment by esod** [comment]
We broke them. They're not broken on COD oob.

We can continue with OG active in our stack. But then we won't be able to update/override the features modules which means no new configuration can be added in code. I think we can do better than this.

**Comment by ForestMars** [comment]
What are you talking about? Broken how? What are the steps to reproduce?

All I am seeing are the normal features overrides. AFAICT, the modules are not broken, they just need to be updated. 

If you can explain what you mean by "broken" maybe write that up and post it somewhere else, I'm not sure this thread is very useful at this point and is starting to border on FUD.

**Comment by esod** [comment]
I assure you It's not my FUD. If you are voting no @ForestMars for proceeding with development on the site by disabling OG, that is your vote and your right. 

One way that Features modules can be permanently broken is when a field is deleted in the admin and then recreated with exactly the same attributes. It's possible this happened last Monday.

How can I continue to develop site if I can't save any more configuration in code? What I mean by we  can do better is we can do better than build a Drupal site whose configuration is controlled by ticking checkboxes in the admin.

**Comment by willykaram** [comment]
In the hopes of trying to resolve this, I spent a bit of time researching and testing everything again, but went a bit deeper this time than we did earlier in the week.

Simple solution seems to be to update OG.

Apologies in advance for the long post, but wanted to be thorough in the hopes we can quickly resolve this.

**Short Version**

The short version is that updating OG to the latest version with Drush resolves the issue that we ran into (i.e., updating from 7.2.4 to 7.2.5). I did a bunch of QA after updating, and the issue seems to be resolved without any other new issues arising. Before realizing this, I thoroughly reviewed the DB without success, which made me look to the code again. When doing so I realized that the 2013 site is running OG 7.2.2 and the 2014 site is running OG 7.2.4. If you want to see more detail read below. But the simple solution for now seems to be to upgrade the module, hopefully everyone is ok with that. Can someone else try this out to confirm as well and then ideally we can put this issue to bed? If so, thanks to everyone for putting in as much effort as we all did, especially Eric who did a bunch it and Forest for encouraging us to be diligent.

**Long Version**

Before taking the above simple OG update route, I spent some more time today thoroughly reviewing all the relevant areas of the 2013 vs 2014 databases, and all the settings were identical. This is what lead me back to looking at the code. In particular, I reviewed relevant row-by-row:
- The system table (and relevant fields: bootstrap, weight, schema, etc.);
- The field tables (field_config & field_config_instance); 
- The OG tables (each from _membership ... to ... _roles); 
- The core user, roles, permissions, etc.;
- The url_alias and menu_router independently and against the OG code to make sure weren't somehow screwing up callbacks; and
- Out of an abundance of caution, event the node_access and rules tables.

Simply put, I went through all the relevant DB tables, and everything was identical. I even when so far as to diff the lengthy nested array field configs,and everything was identical. This left me stumped, as it meant that our problem had to be in either a module, profile or features code.

I reviewed the issue queue again -- essentially the same as last time around:

https://drupal.org/node/1906750
https://drupal.org/node/1906750
https://drupal.org/node/1906750
https://drupal.org/node/1678202

The answer was there, I think we just missed it last time, see: 

https://drupal.org/comment/8176637#comment-8176637

It appears that there was a bug in OG. Unfortunately when reviewing things earlier in the week, I assumed that we were still running the same version of OG in the 2014 codebase as in 2013, and that we didn't upgrade (presumably b/c COD hadn't) -- silly assumption and bad practice, I know However, the 2013 site is currently running 7.2.2; whereas the 2014 site is currently running 7.2.4. As per comment 14 in the issue noted above, the issue specifically appears to relate to the OG node access functionality:

```
if (entityreference_get_selection_handler($field, $instance)->getReferencableEntities(NULL, 'CONTAINS', 1)) {
  return NODE_ACCESS_ALLOW;
}
```

vs

```
if (entityreference_get_selection_handler($field, $instance)->countReferencableEntities()) {
   return NODE_ACCESS_ALLOW;
}
```

I checked the diff and don't see the fix form the comment/patches there in 7.2.5 vs .4; but presumably it was resolved elsewhere and in principle the fix note above is pretty clear. I don't have time to dig through to see where the fix actually was made, but others are welcome too if they wish.  As mentioned above, I did a bunch of QA w/out encountering any issues, including testing w/different users, adding content, adding/adjusting fields (incl. the OG audience fields at issue), and rebuilding permissions.

Although we should be certain to update OG with Drush, it's also worth noting simply dropping in the 7.2.5 OG code was enough to resolve the issue (w/out even clearing the cache or updating the DB) -- so it would seem be a fix along the lines of the above in the codebase.

Hopefully everyone is ok with the quick fix up updating to the latest version of OG.

**Comment by likewhoa** [comment]
ok talking with @willykaram on irc, I did the og upgrade from 7.2.4 to 7.2.5 which is the stable and recommended version on http://dgo.to/og and the node/add for anonymous users is denied but for authenticated users they are shown Event and Session content types with the former a permission set for the authenticated role. 

Anyways, it seems that og 7.2.4 is at fault here which is great news. Thanks @willykaram for the excellent troubleshooting. :+1: to you my friend.

I think this issue can be closed after upgrading og now :100:

**Comment by ForestMars** [comment]
This one's for you, Willy: http://drupaltv.org/video/tutti-fan-drupal (jump to 27:51)

**Comment by likewhoa** [comment]
Just note that we just have to `drush dl og && rm -rf profiles/cod/modules/contrib/og && mv sites/all/modules/og profiles/cod/modules/contrib/og && drush updb` and then remove ability for authenticated users to create event nodes.

**Comment by likewhoa** [comment]
reopening so that we can first test #83 as that's what a good QA does.

**Comment by willykaram** [comment]
Thanks @likewhoa, hopefully someone can review/do the QA on this (@esod would be ideal if he has time, since he's done a bunch of great work around this already and is up to speed). Ideally all goes smoothly and then we can switch gears to theming, and some of the other high priority items.

**Comment by willykaram** [comment]
@likewhoa BTW, if someone else doesn't tackle the PR tomorrow I can, but likely best not for me to do so. Thanks for jumping on this tonight.

**Comment by esod** [comment]
Great stuff. I'll review the pull request.

**Comment by likewhoa** [comment]
All done here, lets focus on other issues now \o/
