### ISSUE TITLE
Alert all themers to commit to `themeup` branch

### ISSUE THREAD

**Issue by jonpugh** [NYC-Camp/website#89]
The `themeup` branch of the main `NYC-Camp/website` repo is going to the multidev environment at http://themeup-nyccamp2014.gotpantheon.com/

Please alert all themers to commit to this branch, or submit pull requests to this branch.

Do NOT commit or merge to Master until work is complete and QA testing has happened on the http://themeup-nyccamp2014.gotpantheon.com/ site.

thanks!

**Comment by jonpugh** [comment]
@timhobert: We had to revert your commits to master because the CSS wasn't ready.

You will have to merge from master (which will bring those reverts to branch `themeup`) and manually recreate and commit your changes.  

Thanks,
Jon

**Comment by mirie** [comment]
Can close this out now :)
