### ISSUE TITLE
node edit styles not respected

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#9]
For example, regardless whether I use the rich-text wysiwyg editor, or disable rich-text and add the tags directly, styles are not being displayed correctly but are just being wrapped in a .p1 class p tag:

http://nyccamp.org/event/security-summit

Tested against Full HTML filter; I didn't try Raw HTML filter bc we really shouldn't be using that.

**Comment by mirie** [comment]
Can you be more specific in terms of the styles you are trying to use? I tried bold and italics without issue (on dev) for the same node.

**Comment by mirie** [comment]
@ForestMars, Any additional problems with this?

**Comment by ForestMars** [comment]
Nope, looks all good now!
