### ISSUE TITLE
Featured Attendees

### ISSUE THREAD

**Issue by willykaram** [NYC-Camp/website#93]
One feature of which we are in somewhat desperate/immediate need is the ability to promote featured attendees on the homepage of the NYC Camp site. This would appear in a block on the homepage beneath the main header, and would need to involve either a slideshow or preferably a carousel. For examples, see:

http://szeged2014.drupaldays.org/
http://2013.badcamp.net/

**Comment by willykaram** [comment]
I'm posting a second comment with the suggest architectural/theming approach, but ultimately that;s up to @likewhoa or whoever decides to tackle this. My suggest approach is a simple view of users where we display there profile photo, full name and user name in a carousel, so that we are simply re-using all that architecture. However, it would also be ideal to be able to display some additional information about each of those users that explains why they are "featured attendees".

For instance, Holly Ross and Angie Byron would ideally both be featured on the homepage. However many new attendees won't know who they are. As such it'd be nice to be able to provide a bit of supplemental blurb about each of them that provides some additional info. We could add this additional info by way of a field on the user profile with field perms so that only site admin can add that, using profile 2, or with an entity/node (none of these solution are ideal, all have drawback, but I suggest the first). We can the use Beauty Tips or another method to display the blurb when hovering over the featured attendee.

**Comment by willykaram** [comment]
Additionally, we will ideally write about 1-2 news posts per week about featured attendees, and it would be nice to be able to have the featured attendees in the view be clickable and link to that new post. Architecturally, we could do this with a user "Related Attendees" field on news content type which associates users with a news post, and then use a reverse reference lookup and relation on the above view to link the users in the carousel back to the news post. This lat suggestion is definitely a 'nice to have feature', and not essential. For now we should just focus on the carousel and then ideally blurb on hover (which would be gravy).

**Comment by willykaram** [comment]
Pick your poison:

https://drupal.org/node/418616
https://drupal.org/project/jcarousel
https://drupal.org/project/views_slideshow_jcarousel
https://drupal.org/project/views_slideshow_liquidcarousel

Among other options

**Comment by rabellamy** [comment]
@willykaram would you consider https://github.com/Team-Sass/toolkit#carousels? It would be mobile friendly.....

**Comment by ForestMars** [comment]
@rabellamy +1 if you can answer how do we wire sass toolkit carousels up to views?

**Comment by rabellamy** [comment]
leverage views templates and strip out all unnecessary markup .... we got to be lean and mean!

http://rabellamy.github.io/na-gallery/index.html

**Comment by mirie** [comment]
@likewhoa is already working on a version using flexslider.

Btw, I experimented with that Beautytip and it didn't work so with mobile.

**Comment by likewhoa** [comment]
@rabellamy do like but our current theme is not even sass,compass ready which doesn't make sense  as I know zen supports it. Why didn't we set this up from the beginning? I am normally using aurora and or omega4 and this is the norm on those, my experience with since was way back before sass was even introduced.

**Comment by likewhoa** [comment]
Beginning of the carousel (un-themed) http://featnd-93-nyccamp2014.gotpantheon.com/team 

Only thing missing is 'related news' link but is this going to be a link from what [picture],[full_name] or [username]?

**Comment by willykaram** [comment]
@likewhoa Thanks, this is _really_ starting to come together! Can you possibly take care ofsome theming/customization for the carousel:
- Ensuring the view is in a block with the title "Featured Attendees", that way we can place it in the homepage;
- Set the carousel to auto advance if possible (I think this is supported in FlexSlider).
- Adding and image cache setting that we can tweak, e.g., with images about 75% larger and making theme B&W for now (we may do a slight blue or white retouch to later);
- Tightening up the names/handles, with name first and handle second;
- Making the name/handle linkable as well;
- Ideally having the name/handle over the bottom of the image with a semi-transparent gray background.
  Sorry we're theming it blind/in the fly, but totally appreciate all the work on this!

**Comment by likewhoa** [comment]
@willykaram name/handle over carousel thumbnail not gonna fit so well, can we just have them on the bottom of   the image?

on mobile having name/handle overlay over image will be to crowded and on frontpage as well unless we make carousel only show like 3 images at a time.

Points 1,2,3,4,5 are taken care of atm.

**Comment by willykaram** [comment]
@likewhoa sweet thanks. Instead over overlaying the name just tighten it up underneath and make it smaller ask that it all fit, similar to the BADCamp example: http://2013.badcamp.net. This should get use far online that we can go live. Then further design/theming could be done as we progress if time permits.

**Comment by likewhoa** [comment]
Added some theming, let me know if this look is better.

**Comment by willykaram** [comment]
Thanks for knocking this out of the park @likewhoa. We still have a few small tweaks, but it already looks super!!
