### ISSUE TITLE
Twitter block is broken? 

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#94]
Latest tweet showing in the front page Twitter block is from 2/27

**Comment by jmarkel** [comment]
@ForestMars I'm seeing one from mortendk from march 4

**Comment by ForestMars** [comment]
Weird. So it appears it stopped working from 2/27 up until that tweet?

**Comment by jmarkel** [comment]
The only @NYCCampDrupal tweets between 2/27 and 3/4 were replies, not
broadcast tweets (i.e. they started with @username). I guess the Twitter
block doesn't show those.

**Comment by ForestMars** [comment]
Ok, closing but would be god to keep an eye on this.
